version: "3.8"
services:
  backend:
    build: backend
    container_name: backend
    stop_signal: SIGINT
    ports:
      - "10000:10000"
    depends_on:
      - "postgres"

  postgres:
    build: database
    container_name: backend-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: names
